///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Categories {
/*
{
  "id": 1,
  "name": "Category 1",
  "created_at": "2024-03-16T14:09:26.000000Z",
  "updated_at": "2024-03-16T14:09:26.000000Z"
} 
*/

  int? id;
  String? name;
  String? createdAt;
  String? updatedAt;

  Categories({
    this.id,
    this.name,
    this.createdAt,
    this.updatedAt,
  });
  Categories.fromJson(Map<String, dynamic> json) {
    id = int.tryParse(json['id']?.toString() ?? '');
    name = json['name']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}
